### ISSUE TITLE
cross build failed since ggml-sys 0.1.0

### ISSUE THREAD

**Issue by hlhr202** [rustformers/llama-rs#101]
Hi, llama-node author here. Would like to know how to cross compile for ggml-sys? I m compiling apple arm64 on Ubuntu WSL2

command is 
```
cargo build --release --target aarch64-apple-darwin
```

the printed error
```
error: failed to run custom build command for `ggml-sys v0.1.0 (https://github.com/rustformers/llama-rs.git?branch=main#57440bff)`

Caused by:
  process didn't exit successfully: `/home/hlhr202/workspace/llama-node/target/release/build/ggml-sys-fa5fcd66bb36a9eb/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-changed=ggml
  OPT_LEVEL = Some("3")
  TARGET = Some("aarch64-apple-darwin")
  HOST = Some("x86_64-unknown-linux-gnu")
  cargo:rerun-if-env-changed=CC_aarch64-apple-darwin
  CC_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=CC_aarch64_apple_darwin
  CC_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=TARGET_CC
  TARGET_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  RUSTC_LINKER = Some("/home/hlhr202/.cache/napi-rs-nodejs/zig-linker-aarch64-apple-darwin.sh")
  cargo:rerun-if-env-changed=CROSS_COMPILE
  CROSS_COMPILE = None
  cargo:rerun-if-env-changed=CFLAGS_aarch64-apple-darwin
  CFLAGS_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=CFLAGS_aarch64_apple_darwin
  CFLAGS_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=TARGET_CFLAGS
  TARGET_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("aes,crc,dit,dotprod,dpb,dpb2,fcma,fhm,flagm,fp16,frintts,jsconv,lor,lse,neon,paca,pacg,pan,pmuv3,ras,rcpc,rcpc2,rdm,sb,sha2,sha3,ssbs,vh")
  cargo:rustc-link-lib=framework=Accelerate
  running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-arch" "arm64" "-I" "include" "-mcpu=native" "-pthread" "-DGGML_USE_ACCELERATE" "-DNDEBUG" "-o" "/home/hlhr202/workspace/llama-node/target/aarch64-apple-darwin/release/build/ggml-sys-132533d640c61337/out/ggml/ggml.o" "-c" "ggml/ggml.c"
  cargo:warning=cc: warning: ‘-mcpu=’ is deprecated; use ‘-mtune=’ or ‘-march=’ instead
  cargo:warning=cc: error: unrecognized command-line option ‘-arch’
  exit status: 1

  --- stderr


  error occurred: Command "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-arch" "arm64" "-I" "include" "-mcpu=native" "-pthread" "-DGGML_USE_ACCELERATE" "-DNDEBUG" "-o" "/home/hlhr202/workspace/llama-node/target/aarch64-apple-darwin/release/build/ggml-sys-132533d640c61337/out/ggml/ggml.o" "-c" "ggml/ggml.c" with args "cc" did not execute successfully (status code exit status: 1).


warning: build failed, waiting for other jobs to finish...
You are cross compiling aarch64-apple-darwin on linux host
Internal Error: Command failed: cargo build --release --target aarch64-apple-darwin
    at checkExecSyncError (node:child_process:828:11)
    at Object.execSync (node:child_process:902:15)
    at BuildCommand.<anonymous> (/home/hlhr202/workspace/llama-node/packages/core/node_modules/@napi-rs/cli/scripts/index.js:11474:30)
    at Generator.next (<anonymous>)
    at fulfilled (/home/hlhr202/workspace/llama-node/packages/core/node_modules/@napi-rs/cli/scripts/index.js:3509:58)
```

**Comment by philpax** [comment]
Hmm, did this work before the `ggml-sys` change? The error seems to be about

`"-arch" "arm64"`

and I can't see any reason why that would have changed with the changes to the build script.

**Comment by hlhr202** [comment]
> Hmm, did this work before the `ggml-sys` change? The error seems to be about
> 
> `"-arch" "arm64"`
> 
> and I can't see any reason why that would have changed with the changes to the build script.

@philpax yes, previously I did not get any cross build error on Ubuntu.

**Comment by hlhr202** [comment]
https://github.com/rustformers/llama-rs/blob/main/ggml-sys/build.rs#L6
is this the case i need to handle actually?

**Comment by philpax** [comment]
Yeah sorry I've been busy, I'd suggest removing these two lines and see if they have any impact https://github.com/rustformers/llama-rs/blob/main/ggml-sys/build.rs#L59

If they do I'll see if I can rewire things so those aren't active for cross-compilation

**Comment by hlhr202** [comment]
> Yeah sorry I've been busy, I'd suggest removing these two lines and see if they have any impact https://github.com/rustformers/llama-rs/blob/main/ggml-sys/build.rs#L59
> 
> If they do I'll see if I can rewire things so those aren't active for cross-compilation

okay will try soon and reply here

**Comment by hlhr202** [comment]
> Yeah sorry I've been busy, I'd suggest removing these two lines and see if they have any impact https://github.com/rustformers/llama-rs/blob/main/ggml-sys/build.rs#L59
> 
> If they do I'll see if I can rewire things so those aren't active for cross-compilation

@philpax It is not caused by mcpu. and I guess the problem was not from build script. I revert it to previous build script, still throw error.

**Comment by philpax** [comment]
If I were to guess, your cross compiler doesn't support compiling for another architecture, or the syntax used to specify cross compilation is different to what `cc` expects.

**Comment by hlhr202** [comment]
> If I were to guess, your cross compiler doesn't support compiling for another architecture, or the syntax used to specify cross compilation is different to what `cc` expects.

maybe. I can cross compile to x86 linux from a arm64 macos, but will lost acceleration features...

**Comment by philpax** [comment]
You should be able to specify the target features if you're cross-compiling - try `RUSTFLAGS='-C target-features=fma,avx,avx2,f16c,sse3'` as an env variable in your arm64 -> x86-64 build.

**Comment by hlhr202** [comment]
@philpax I m now switched to github multi platform runner and it solve the compile error on different os, but I still need to remove -mcpu=native if I want to compile aarch64 darwin from a x86 mac host. is there any workaround for this?
Currently github action does not support arm64 host.

**Comment by hlhr202** [comment]
I created a temporary solution for cross compilation error:
https://github.com/rustformers/llama-rs/pull/111
