### ISSUE TITLE
Update to the latest `llama.cpp` `ggml`

### ISSUE THREAD

**Issue by philpax** [rustformers/llama-rs#118]
Another day, another suite of changes. Since our last update, M1 and AVX inference has improved, as well as a bunch of other improvements: https://github.com/ggerganov/llama.cpp/compare/437e77855a54e69c86fe03bc501f63d9a3fddb0e..HEAD

If you're interested in tackling this, check out our contributing document: https://github.com/rustformers/llama-rs/blob/main/CONTRIBUTING.md

**Comment by philpax** [comment]
Note that this changes the implementation of the LLaMA model - it is *not* a drop-in upgrade!

**Comment by KerfuffleV2** [comment]
I'm working on this one. Just updating the bindings seemed pretty uneventful: some types changed from `i64` to `i32`. After that fix it compiles and appears to function.

Still need to do the actual model change part, which hopefully will put #68 to bed in a permanent way.
