### ISSUE TITLE
Support for GPT-NeoX

### ISSUE THREAD

**Issue by philpax** [rustformers/llama-rs#145]
[GPT-NeoX](https://huggingface.co/docs/transformers/model_doc/gpt_neox) is EleutherAI's newer LLM. It's pretty powerful, but I've never run it myself due to its parameter count.

**Comment by philpax** [comment]
Looks like https://github.com/h2oai/h2ogpt is based on this too

**Comment by philpax** [comment]
@danforbes can you comment on this issue so that I can assign you to it?

**Comment by danforbes** [comment]
> @danforbes can you comment on this issue so that I can assign you to it?

Yes I can 😅 WIP here https://github.com/danforbes/llama-rs/tree/dfo/model/stablelm
