### ISSUE TITLE
Support for StableLM

### ISSUE THREAD

**Issue by philpax** [rustformers/llama-rs#146]
[StableLM](https://github.com/Stability-AI/StableLM) is Stability AI's new, open-source, legally unburdened LLM. I imagine it will be quite popular as a LLM soon due to its ready availability.

I believe it's based on the GPT-NeoX architecture, so #145 will need to be done before this (or at the same time).

Here's the tracking issue for `llama.cpp`: https://github.com/ggerganov/llama.cpp/issues/1063

**Comment by danforbes** [comment]
Based on what I'm seeing [here](https://github.com/ggerganov/ggml/tree/master/examples/stablelm), it looks like this Issue can just be closed in favor of #145. I'm going to get started on porting that code now.
