### ISSUE TITLE
Feature request: multi-line text entry

### ISSUE THREAD

**Issue by dustletter** [rustformers/llama-rs#155]
Llama.cpp's chat mode allows entering multiple lines of text by adding a trailing `\` to each one.  I think this would be a nice feature to have, either by copying the backslash functionality over or by using shift+enter like many chat clients.
(I have this partly working already but I want to make sure there's support before going any farther.)

**Comment by philpax** [comment]
There's an issue for this in #53. Feel free to PR up your solution!

**Comment by dustletter** [comment]
So sorry, I don't know how I overlooked that issue!
