### ISSUE TITLE
Make a Chat like Application

### ISSUE THREAD

**Issue by hhamud** [rustformers/llama-rs#52]
Creating an issue here following discussion in the discord chat.

**Comment by erlend-sh** [comment]
This will be solved by #49

**Comment by hhamud** [comment]
> This will be solved by #49

I specifically want a lightweight cli version with a sliding window for context building. Maybe he could rip that part out of his PR and if he's built the sliding window and integrate that into the library? @karelnagel

**Comment by karelnagel** [comment]
> > This will be solved by #49
> 
> I specifically want a lightweight cli version with a sliding window for context building. Maybe he could rip that part out of his PR if he's built that portion and integrate that into the library? @karelnagel

In my app I just keep the model running and so it has all the previous context for that session. I think it should be quite easy to implement that same logic into the cli as well with some kind of flag. I basically just stole that logic from this PR https://github.com/setzer22/llama-rs/pull/37 .😀

**Comment by setzer22** [comment]
As mentioned on the discord conversation, the real challenge here is extending the context window beyond the current cap of 2048 tokens.

I've tried several experiments to achieve a sliding context window, but nothing that gave good results so far. So for now, I'm trying to build a bit more understanding of the underlying transformer architecture before I attempt this again.

Other ways of achieving a larger context window would be training a larger model from scratch (unfeasible), or fine tuning an existing model to work with a larger context window. I'm not entirely sure about the effectiveness of the latter strategy.

**Comment by philpax** [comment]
This is related to #53 and #76.

**Comment by philpax** [comment]
This now exists in the CLI, but it doesn't have a sliding window. Closing this issue and moving discussion to #77.
