### ISSUE TITLE
Update to latest llama.cpp

### ISSUE THREAD

**Issue by philpax** [rustformers/llama-rs#62]
There have been quite a few changes since our last major sync: https://github.com/ggerganov/llama.cpp/compare/904d2a8d6acd667c9633138d45a361d40fbf76d0..HEAD

(There may be others we haven't accounted for in the inferencing code).

Need to do a more precise breakdown, but

- #59 and #61

**Comment by iacore** [comment]
I met the `InvalidMagic` error again, after #61. Is there another breaking change in ggml format?

**Comment by philpax** [comment]
Yep, #93.
