### ISSUE TITLE
Using cached sessions in REPL mode ?

### ISSUE THREAD

**Issue by nsarrazin** [rustformers/llama-rs#88]
Hi everyone!

I've been using  `llama-rs` recently and I especially love the caching session feature. I've been building an API that allows users to maintain multiple conversation threads and switch between them on the fly.

This means I'm currently caching each conversation using a unique id, and loading them as needed depending on which conversation the user is talking to. It works great and the response time are pretty fast on deep conversations but it also means I need to load the weights into memory each time. 

As far as I know it's not possible to use cached sessions in REPL mode. On some setups with slower disk I/O this is now the bottleneck on chats.

Would there be a way for me to achieve something like this ? To recap:
* Binary stays loaded in memory in REPL mode.
* For every prompt in REPL mode, pass a **different** cached session so it can load context before answering, and save the results after. 

Feel free to let me know if you think this is technically possible and just not exposed in the CLI, or if there's some deeper issue making this harder to achieve.

Thank you for your time, I'm a big fan of this project. :D

**Comment by philpax** [comment]
Hey, thanks for reporting this! Just noticed now that we don't wire up loaded sessions to the REPL - that should be easy enough to fix.

With switching out the cached sessions per prompt, I think that'd be out of scope for the CLI, but that should be easy enough to implement. You can see that session loading is done here:

https://github.com/rustformers/llama-rs/blob/main/llama-cli/src/main.rs#L224-L244

and the REPL just runs in a loop, feeding the user prompt to the session:

https://github.com/rustformers/llama-rs/blob/main/llama-cli/src/main.rs#L21-L63

So all you'd have to do is load the model once, and for each session: load an existing session if required, run inference, and then persist the session back to disk.

**Comment by nsarrazin** [comment]
Thanks for the quick update!

I'll try to implement the switching of the cache myself, never worked with Rust but I'll give it a go it should be fun. Thanks for pointing me in the right direction.
