### ISSUE TITLE
Relicense as MIT/Apache2

### ISSUE THREAD

**Issue by philpax** [rustformers/llama-rs#92]
The going standard in the Rust ecosystem is MIT/Apache2 for a variety of reasons. Here's Bevy's PR for more context: https://github.com/bevyengine/bevy/issues/2373

I suggest we do this sooner rather than later (we'll need the consent of all contributors)

**Comment by setzer22** [comment]
No objections with the change :+1:

I'll just ping everyone who has merged changes so far to make people aware of this (and sorry all about the ping):

- @KerfuffleV2 
- @RoyVorster 
- @odysa
- @jempabroni 
- @Metalflame12 
- @bcho 
- @darthdeus 
- @trizko 
- @mwbryant

**Comment by KerfuffleV2** [comment]
No objections here. Slightly changed version of the suggested "agreeing to the change" language:

*I license my past and future contributions to this project under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.*

**Comment by bcho** [comment]
I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by Metalflame12** [comment]
I license my past and future contributions to this project under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by mwbryant** [comment]
I license my past and future contributions to this project under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by trizko** [comment]
I license my past and future contributions to this project under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by odysa** [comment]
I license my past and future contributions to this project under the dual MIT/Apache-2.0 license, allowing licensees to choose either at their option.

**Comment by darthdeus** [comment]
I license all my contributions under whatever license the authors choose at whatever point in time in the future, including but not limited to MIT/Apache-2.0.

**Comment by philpax** [comment]
@RoyVorster ping

**Comment by philpax** [comment]
I've been unsuccessful in contacting Roy, but I believe that #125 will more or less replace all of the code he's contributed, so we should be in the clear. Given that, I'll proceed with the relicensing once all of our pending PRs are in.
